version: '3'

services:
  mongodb1:
    build: ./mongo
    restart: always
    container_name: mongodb1
    volumes:
      - mongodata1:/data/db
    expose:
      - "27017"
    ports:
      - 27017:27017
    environment:
      - PORT=27017
      - IS_PRIMARY=YES

  mongodb2:
    build: ./mongo
    restart: always
    container_name: mongodb2
    volumes:
      - mongodata2:/data/db
    expose:
      - "27018"
    ports:
      - 27018:27018
    environment:
      - PORT=27018
    
  mongodb3:
    build: ./mongo
    restart: always
    container_name: mongodb3
    volumes:
      - mongodata3:/data/db
    expose:
      - "27019"
    ports:
      - 27019:27019
    environment:
      - PORT=27019

volumes:
  mongodata1:
  mongodata2:
  mongodata3:
